- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    home_dir: "{{ lookup('env','HOME') }}/"

    app_setting_links:
      # - { src: private.xml, dest: Library/Application\ Support/Karabiner/private.xml }
    brew_taps:
      - neovim/neovim
      - laurent22/massren
      - homebrew/cask-versions
      - github/gh

    brew_cask_priority_high:
      - { name: java }
      - { name: xquartz }
    brew_priority_high:
      - { name: bash }
      - { name: zsh }
      - { name: fish }
      - { name: bash-completion@2 }
      - { name: python }
      - { name: python3 }
      - { name: ansible }
      - { name: carthage }
      - { name: sbt }
      - { name: haskell-stack }
      - { name: curl }
      - { name: direnv }
      - { name: fswatch }
      - { name: gpg }
      - { name: gnu-sed }
      # - { name: google-cloud-sdk }
      # - { name: qt5 } # can't install 10.12
      - { name: wget }
      - { name: openssl }
      # - { name: openssl, state: linked, install_options: force }  # can't make link with brew's openssl
      - { name: icdiff }
      - { name: ammonite-repl }
      - { name: terminal-notifier }
      - { name: tree }
      - { name: exa }
      - { name: fd }
      - { name: bat }
      - { name: ripgrep }
      - { name: tmux }
      - { name: peco }
      - { name: fzf }
      - { name: reattach-to-user-namespace }
      - { name: git }
      - { name: git-flow }
      - { name: hub }
      - { name: git-delta }
      - { name: gh }
      - { name: tig }
      - { name: shellcheck }
      - { name: readline }
      - { name: ghostscript }
      - { name: nginx }
      - { name: fping }
      - { name: htop }
      - { name: rsync }
      - { name: unison }
      - { name: ag }
      - { name: bison }
      - { name: coreutils }
      - { name: icu4c }
      - { name: libtool }
      - { name: unixodbc }
      - { name: unzip }
      - { name: ctags }
      - { name: figlet }
      - { name: jq }
      - { name: jid }
      - { name: massren }
      - { name: gdb }
      - { name: rmtrash }
      - { name: gnu-tar }
      - { name: highlight }
      - { name: mcrypt }
      - { name: re2c }
      - { name: jpeg }
      - { name: libxml2 }
      - { name: libxml2, state: linked, install_options: force }
      - { name: libxslt }
      - { name: libiconv }
      - { name: libpng }
      - { name: giflib }
      - { name: webp }
      - { name: glslang }
      - { name: vim }
      - { name: neovim }
      - { name: autoconf }
      - { name: automake }
    brew_priority_normal:
      - { name: ffmpeg }

    brew_cask_priority_normal:
      # browser, mailer, and apps for web services
      - { name: google-chrome }
      - { name: google-chrome-canary }
      - { name: firefox }
      - { name: firefox-developer-edition }
      - { name: brave-browser }
      - { name: safari-technology-preview }
      - { name: bathyscaphe }
      - { name: skype }

      # development
      - { name: alacritty }
      - { name: atom }
      - { name: db-browser-for-sqlite }
      - { name: diffmerge }
      - { name: docker }
      # - { name: emacs }
      - { name: ngrok }
      - { name: postman }
      # - { name: teamsql }
      # - { name: rdm }
      - { name: another-redis-desktop-manager }
      - { name: robo-3t }
      - { name: sequel-pro }
      - { name: sourcetree }
      - { name: switchhosts }
      - { name: vagrant }
      - { name: visual-studio-code }
      - { name: wireshark }

      # utility
      - { name: alfred }
      - { name: anki }
      - { name: appcleaner }
      - { name: bettertouchtool }
      # - { name: bitwarden } install from app store
      - { name: caffeine }
      - { name: diskmaker-x }
      - { name: diskwave }
      - { name: dropbox }
      - { name: duet }
      - { name: flux }
      - { name: google-backup-and-sync }
      - { name: google-japanese-ime }
      - { name: karabiner-elements }
      - { name: keka }
      - { name: kindle }
      - { name: path-finder }
      - { name: station }
      - { name: toggl }
      # - { name: totalspaces }
      - { name: teensy }
      - { name: tweet-tray }
      - { name: iina }
      - { name: vlc }
      - { name: zoomus }
      - { name: discord }
      - { name: lastfm }
      - { name: xld }
      - { name: skyfonts }

      # shareware
      - { name: jetbrains-toolbox }
      - { name: adobe-creative-cloud }

      # QuickLook
      # - { name: betterzipql }
      - { name: epubquicklook }
      - { name: qlcolorcode }
      #- { name: qldds }    # sha256 error
      - { name: qlimagesize }
      - { name: qlmarkdown }
      - { name: qlnetcdf }
      - { name: qlprettypatch }
      - { name: qlswift }
      - { name: qlrest }
      - { name: qlstephen }
      - { name: qlvideo }
      - { name: quicklook-csv }
      - { name: quicklook-json }
      - { name: quicknfo }
      - { name: scriptql }
      - { name: webpquicklook }
    vagrant_plugins:
      - sahara
      - dotenv
      - vagrant-vbguest
      - vagrant-vbox-snapshot
      - vagrant-parallels
      - vagrant-hostsupdater
  tasks:
    # Mac setting
    # - name: preview text copy
    #   osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true

    - name: stop Automatic Capitalization
      osx_defaults: domain=NSGlobalDomain key=NSAutomaticCapitalizationEnabled type=bool value=false

    - name: minimize to application icon
      osx_defaults: domain=com.apple.dock key=minimize-to-application type=bool value=true

    - name: set dock tilesize
      osx_defaults: domain=com.apple.dock key=tilesize type=float value=30

    - name: set dock large-tilesize
      osx_defaults: domain=com.apple.dock key=largesize type=float value=50

    - name: don't write DS_Store files on Network stores
      osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true

    - name: don't write DS_Store files on Network stores
      osx_defaults: domain=com.apple.desktopservices key=DSDontWriteUSBStores type=bool value=true

    - name: show all filename extensions
      osx_defaults: domain=NSGlobalDomain key=AppleShowAllExtensions type=bool value=false

    - name: show status bar
      osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true

    - name: show path bar
      osx_defaults: domain=com.apple.finder key=ShowPathBar type=bool value=true

    - name: keep folders on top when sorting by name
      osx_defaults: domain=com.apple.finder key=_FXSortFoldersFirst type=bool value=true

    - name: stop extension change warning
      osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=true

    - name: stop empty trash warning
      osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=true

    - name: set Key Repeat Speed
      osx_defaults: domain="Apple Global Domain" key=KeyRepeat type=int value=2

    - name: set Initial Key Repeat Speed
      osx_defaults: domain="Apple Global Domain" key=KeyRepeat type=int value=15

    # homebrew -------------------------------------------------
    - name: tap repositries
      homebrew_tap: tap={{ item }} state=present
      with_items: '{{brew_taps}}'

    - name: update & upgrade homebrew
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: install brew cask priority-high packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('present') }}
      with_items: '{{brew_cask_priority_high}}'

    - name: install brew priority-high packages
      homebrew: name={{ item.name }} state={{ item.state|default('latest') }} install_options={{ item.install_options|default() }}
      with_items: '{{brew_priority_high}}'

    - name: install brew priority-normal packages
      homebrew: name={{ item.name }} state={{ item.state|default('latest') }} install_options={{ item.install_options|default() }}
      with_items: '{{brew_priority_normal}}'

    - name: install brew cask priority-normal packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('present') }}
      with_items: '{{brew_cask_priority_normal}}'

    # sym links -------------------------------------------------
    - name: install links & some plugins
      shell: "{{ home_dir }}/dotfiles/_setup.py"

    # add shell
    - name: add shells path
      lineinfile: path=/etc/shells line=/usr/local/bin/{{ item }}
      become: yes
      with_items:
        - bash
        - zsh
        - fish

    # add key
    - name: add key for sbt
      shell: "gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv 99E82A75642AC823"

    # Vagrant
    - name: install vagrant plugins
      command: vagrant plugin install {{ item }}
      with_items: '{{vagrant_plugins}}'

