- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    home_dir: "{{ lookup('env','HOME') }}/"

    app_setting_links:
      # - { src: private.xml, dest: Library/Application\ Support/Karabiner/private.xml }
    brew_taps:
      - neovim/neovim
      - laurent22/massren
      - homebrew/cask-versions
      - homebrew/cask-fonts
      - hashicorp/tap
      - github/gh
      - daipeihust/tap

    brew_cask_priority_high:
      - { name: xquartz }
    brew_priority_high:
      - { name: bash }
      - { name: zsh }
      - { name: fish }
      - { name: bash-completion@2 }
      - { name: java }
      - { name: python3 }
      - { name: go }
      - { name: ansible }
      - { name: carthage }
      - { name: sbt }
      - { name: haskell-stack }
      - { name: curl }
      - { name: direnv }
      - { name: fswatch }
      - { name: gpg }
      - { name: gnu-sed }
      - { name: wget }
      - { name: openssl }
      # - { name: openssl, state: linked, install_options: force }  # can't make link with brew's openssl
      - { name: icdiff }
      - { name: terminal-notifier }
      - { name: tree }
      - { name: exa }
      - { name: fd }
      - { name: bat }
      - { name: fzf }
      - { name: ripgrep }
      - { name: tmux }
      - { name: reattach-to-user-namespace }
      - { name: git }
      - { name: git-flow }
      - { name: hub }
      - { name: git-delta }
      - { name: gh }
      - { name: tig }
      - { name: im-select } # For VS Code's VIM extension
      - { name: shellcheck }
      - { name: readline }
      - { name: ghostscript }
      - { name: nginx }
      - { name: fping }
      - { name: htop }
      - { name: rsync }
      - { name: unison }
      - { name: ag }
      - { name: bison }
      - { name: coreutils }
      - { name: icu4c }
      - { name: libtool }
      - { name: unixodbc }
      - { name: unzip }
      - { name: ctags }
      - { name: figlet }
      - { name: jq }
      - { name: jid }
      - { name: massren }
      - { name: trash }
      - { name: gnu-tar }
      - { name: highlight }
      - { name: mcrypt }
      - { name: re2c }
      - { name: jpeg }
      - { name: libxml2 }
      - { name: libxml2, state: linked, install_options: force }
      - { name: libxslt }
      - { name: libiconv }
      - { name: libpng }
      - { name: giflib }
      - { name: webp }
      - { name: glslang }
      - { name: vim }
      - { name: neovim }
      - { name: autoconf }
      - { name: automake }
      - { name: awscli }
      - { name: google-cloud-sdk }
      # - { name: bazel }
      - { name: bazelisk }
      - { name: buildifier }
      - { name: lefthook }
    brew_priority_normal:
      - { name: ffmpeg }

    brew_cask_priority_normal:
      # browser, mailer, and apps for web services
      - { name: google-chrome }
      - { name: google-chrome-canary }
      - { name: firefox }
      - { name: firefox-developer-edition }
      # - { name: brave-browser }
      - { name: safari-technology-preview }
      - { name: skype }

      # development
      - { name: alacritty }
      - { name: another-redis-desktop-manager }
      - { name: atom }
      - { name: db-browser-for-sqlite }
      - { name: diffmerge }
      - { name: docker }
      - { name: dotnet }
      - { name: figma }
      - { name: gitup }
      # - { name: iterm2 }
      - { name: ngrok }
      - { name: postman }
      - { name: robo-3t }
      - { name: sequel-pro }
      - { name: sourcetree }
      - { name: switchhosts }
      - { name: typora }
      - { name: vagrant }
      - { name: visual-studio-code }
      - { name: wireshark }

      # utility
      - { name: alfred }
      - { name: anki }
      - { name: appcleaner }
      - { name: authy }
      - { name: bettertouchtool }
      - { name: diskmaker-x }
      - { name: diskwave }
      - { name: dropbox }
      - { name: duet }
      - { name: editaro }
      - { name: google-drive }
      - { name: google-japanese-ime }
      - { name: karabiner-elements }
      - { name: keka }
      - { name: kindle }
      - { name: obsidian }
      - { name: pushplaylabs-sidekick }
      - { name: shifty }
      # - { name: toggl }
      - { name: teensy }
      - { name: iina }
      - { name: vlc }
      # - { name: zoomus }
      - { name: discord }
      - { name: xbar }
      - { name: xld }

      # shareware
      - { name: jetbrains-toolbox }
      # - { name: adobe-creative-cloud }

      # QuickLook
      # - { name: epubquicklook }
      - { name: qlcolorcode }
      - { name: qldds }
      - { name: qlimagesize }
      - { name: qlmarkdown }
      - { name: qlnetcdf }
      - { name: qlprettypatch }
      - { name: qlswift }
      - { name: qlrest }
      - { name: qlstephen }
      - { name: qlvideo }
      - { name: quicklook-csv }
      - { name: quicklook-json }
      - { name: quicknfo }
      - { name: scriptql }
      - { name: webpquicklook }
      - { name: apparency }
      - { name: quicklookase }

      # fonts
      - { name: font-sf-arabic }
      - { name: font-sf-mono-for-powerline }
      - { name: font-sf-compact }
      - { name: font-sf-pro }
      - { name: font-sf-mono }
      - { name: font-new-york }
      - { name: font-hackgen }
      - { name: font-hackgen-nerd }
      - { name: font-udev-gothic }
      - { name: font-udev-gothic-nf }
      - { name: font-noto-mono }
      - { name: font-noto-mono-for-powerline }
      - { name: font-noto-sans }
      - { name: font-noto-serif }
      - { name: font-biz-udgothic }
      - { name: font-biz-udmincho }
      - { name: font-biz-udpgothic }
      - { name: font-biz-udpmincho }
      - { name: font-ubuntu }
      - { name: font-ubuntu-mono }
      - { name: font-ubuntu-mono-nerd-font }
      - { name: font-ubuntu-condensed }
      - { name: font-ubuntu-mono-derivative-powerline }
      - { name: font-ubuntu-nerd-font }
      - { name: font-roboto }
      - { name: font-roboto-slab }
      - { name: font-roboto-mono }
      - { name: font-roboto-mono-nerd-font }
      - { name: font-roboto-mono-for-powerline }
      - { name: font-montserrat }

  tasks:
    # Mac setting

    - name: stop Automatic Capitalization
      osx_defaults: domain=NSGlobalDomain key=NSAutomaticCapitalizationEnabled type=bool value=false

    - name: show all filename extensions
      osx_defaults: domain=NSGlobalDomain key=AppleShowAllExtensions type=bool value=false

    # --------------------
    # dock
    # --------------------
    - name: set dock tilesize
      osx_defaults: domain=com.apple.dock key=tilesize type=float value=30

    - name: set dock large-tilesize
      osx_defaults: domain=com.apple.dock key=largesize type=float value=50

    - name: minimize to application icon
      osx_defaults: domain=com.apple.dock key=minimize-to-application type=bool value=true

    # --------------------
    # finder
    # --------------------
    # - name: preview text copy
    #   osx_defaults: domain=com.apple.finder key=QLEnableTextSelection type=bool value=true
    - name: show status bar
      osx_defaults: domain=com.apple.finder key=ShowStatusBar type=bool value=true

    - name: show path bar
      osx_defaults: domain=com.apple.finder key=ShowPathBar type=bool value=true

    - name: keep folders on top when sorting by name
      osx_defaults: domain=com.apple.finder key=_FXSortFoldersFirst type=bool value=true

    - name: stop extension change warning
      osx_defaults: domain=com.apple.finder key=FXEnableExtensionChangeWarning type=bool value=true

    - name: stop empty trash warning
      osx_defaults: domain=com.apple.finder key=WarnOnEmptyTrash type=bool value=true

    - name: set default search target
      osx_defaults: domain="com.apple.finder" key=FXDefaultSearchScope type=string value=SCcf

    - name: set Key Repeat Speed
      osx_defaults: domain="Apple Global Domain" key=KeyRepeat type=int value=2

    - name: set Initial Key Repeat Speed
      osx_defaults: domain="Apple Global Domain" key=KeyRepeat type=int value=15

    # --------------------
    # file systems
    # --------------------
    - name: don't write DS_Store files on Network stores
      osx_defaults: domain=com.apple.desktopservices key=DSDontWriteNetworkStores type=bool value=true

    - name: don't write DS_Store files on USB devices
      osx_defaults: domain=com.apple.desktopservices key=DSDontWriteUSBStores type=bool value=true

    # homebrew -------------------------------------------------
    - name: tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: '{{brew_taps}}'

    - name: update & upgrade homebrew
      homebrew: update_homebrew=yes upgrade_all=yes

    - name: install brew cask priority-high packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('present') }}
      with_items: '{{brew_cask_priority_high}}'

    - name: install brew priority-high packages
      homebrew: name={{ item.name }} state={{ item.state|default('latest') }} install_options={{ item.install_options|default() }}
      with_items: '{{brew_priority_high}}'

    - name: install brew priority-normal packages
      homebrew: name={{ item.name }} state={{ item.state|default('latest') }} install_options={{ item.install_options|default() }}
      with_items: '{{brew_priority_normal}}'

    - name: install brew cask priority-normal packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('present') }}
      with_items: '{{brew_cask_priority_normal}}'

    # add shell
    - name: add shells path
      lineinfile: path=/etc/shells line=/opt/homebrew/bin/{{ item }}
      become: yes
      with_items:
        - bash
        - zsh
        - fish

